---
- name: Reset user password on RHEL 8 and RHEL 9 servers
  hosts: "{{ target_hosts }}"
  become: yes
  vars:
    username: "{{ username }}"
    new_password: "{{ new_password }}"

  tasks:
#    - name: Ensure the user exists
#      ansible.builtin.user:
#        name: "{{ username }}"
#        state: present

#    - name: Reset password for the user
#      ansible.builtin.shell: echo "{{ username }}:{{ new_password }}" | chpasswd
#      args:
#        executable: /bin/bash

    - name: Reset password for the user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ new_password | password_hash('sha512') }}"

    - name: Verify the password has been changed
      ansible.builtin.command:
        cmd: passwd -S "{{ username }}"
      register: password_status

    - name: Display password status
      ansible.builtin.debug:
        msg: "Password status: {{ password_status.stdout }}"
